### ISSUE TITLE
Spat data report should be supported

### ISSUE THREAD

**Issue by hu-weiguo** [open-v2x/dandelion#35]
## Is your feature request related to a problem? Please describe.

Spat data report is not supported.
目前未支持信号机数据上报。

## Describe the solution you'd like

Dandelion should support Spat data report interface. Refer to chapter 5.3.16 of specification for interface between Cooperative Intelligent Transportation System RSU and central subsystem for interface details
应支持信号机数据上报接口，接口详情参考《合作式智能运输系统-RSU与中心子系统间接口规范》第5.3.16章节。

## Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/110092211/182284703-7f35875e-0e0f-4494-8889-7ef066ccff42.png)

## Additional context

None.

**Comment by qiaolei1** [comment]
#107
