### ISSUE TITLE
Spat data sending should be supported

### ISSUE THREAD

**Issue by hu-weiguo** [open-v2x/dandelion#36]
## Is your feature request related to a problem? Please describe.

Spat data sending is not supported.
目前未支持信号机数据下发。

## Describe the solution you'd like

Dandelion should support Spat data sending interface. Refer to chapter 5.3.17 of specification for interface between Cooperative Intelligent Transportation System RSU and central subsystem for interface details
应支持信号机数据下发接口，接口详情参考《合作式智能运输系统-RSU与中心子系统间接口规范》第5.3.17章节。

## Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/110092211/182286172-fb1bf679-4ab9-4e47-a1d2-38d1ae34d0dc.png)

## Additional context

None.

**Comment by qiaolei1** [comment]
#107
