### ISSUE TITLE
The main site cannot connect to subsite

### ISSUE THREAD

**Issue by sacredartr** [open-v2x/dandelion#56]
## Describe the bug

The main site cannot connect to subsite

## Screenshots
<img width="1437" alt="企业微信截图_e82774c7-7278-4485-8682-3d9aa97e303b" src="https://user-images.githubusercontent.com/56632872/185047933-164c96cf-32cb-4432-9fa9-f0e32b9bd4cc.png">
<img width="1401" alt="企业微信截图_f9aa0e7e-1703-49be-bbd7-45fddadc1ede" src="https://user-images.githubusercontent.com/56632872/185047954-3057c1f6-400a-46f5-87ac-48fe5aa7660d.png">

## Log Information

N/A

## Desktop (please complete the following information):

- OS: MACOS
- Browser: chrome
- Version: master/albany

**Comment by wu-wenxiang** [comment]
边缘节点注册 ----> 1. 边缘节点 API -> 数据库写记录 2. 中心节点 API -> 中心节点写数据

配置 1. 边缘节点 API -> 数据库写记录     Restful API / 应该有自身，重启不变的 client ID

注册 2. 中心节点 API -> 中心节点写数据   MQTT -> 失败

心跳 3. 中心节点上看到某个边缘节点断开连接


1. 中心侧需要一组对边缘云节点的 CRUD 接口
2. 中心测需要增加检查边缘节点状态（在线/离线）的接口（可以合并在 1 一起）

**Comment by wu-wenxiang** [comment]
1. 功能设计文档
2. API 设计
3. 大致的实现方案
@乔磊

**Comment by qiaolei1** [comment]
节点注册API ：
        1、边缘节点 应该限制 不能使用和 server 相同的配置 
        2、混合节点 应该限制 要与 server 配置保持一致 
        3、主节点 限制 不能注册 cloud_server 
        4、默认应为混合节点

**Comment by qiaolei1** [comment]
https://zhc3o5gmf9.feishu.cn/docx/doxcnl57r9wgztysfoeBSLmFoMA
